### ISSUE TITLE
onPageUnload funker ikke på iPhone

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#100]

**Comment by mariusmandal** [comment]
alerts are no longer allowed during page dismissal events (beforeunload, unload, pagehide).

document.pagehide

**Comment by mariusmandal** [comment]
document.pagehide og window.unload funker ikke. Vurder å legge JS på alle lenker

**Comment by AsgeirSH** [comment]
Lukker fordi fikset i 7ce87e3 og ikke autolukk via commit.
