### ISSUE TITLE
Noen innslag blir godkjent, men listes ikke opp på Din Side - status feiler?

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#106]

**Comment by AsgeirSH** [comment]
b_status blir ikke lagret i valideringsfunksjonen - selv om den returnerer 8.

**Comment by mariusmandal** [comment]
That's a bug



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Query failer, selv om den funker når jeg kjører den i Toad. Feil SQL-klasse maybe? SQL-klassen har skriverettigheter, right?

**Comment by AsgeirSH** [comment]
Må vel kanskje bytte ut SQL med SQLins, tipper jeg.

**Comment by mariusmandal** [comment]
Sql-klassen har ikke skriverettigheter nei, men sqlins har



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox
