### ISSUE TITLE
GarbageCollector krasjer

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#107]
PermissionDenied-error, kan være tilgangsrettigheter i /var/lib/php5 - i hvert fall verdt å sjekke ut i test/prod-miljø.

Se https://www.dropbox.com/s/8mtl16nkxqi0knp/stacktrace_garbace_clean_crash.pdf?dl=0

**Comment by mariusmandal** [comment]
Kun i dev såvidt vi har klart å påvise
