### ISSUE TITLE
UserBundle: Mobilnummer med åpenrom må fungere

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#110]

**Comment by AsgeirSH** [comment]
Tror nesten du må fikse denne @mariusmandal, den Form-buildern virka ikke helt enkel å hooke seg inn i/før valideringen på.

**Comment by mariusmandal** [comment]
Utgår pga kompleksitet inntil senere utgave

**Comment by AsgeirSH** [comment]
Forbedre feilmelding.

**Comment by AsgeirSH** [comment]
Sjekk UKMUserBundle::Translations::validators.yml

**Comment by AsgeirSH** [comment]
Utgår pga #144-fix. Close.
