### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#12]
Body top margin må reduseres etter jumbo på mobil
.ukm_page_jumbo { margin-top: 15px; }  må bli 0px

**Comment by AsgeirSH** [comment]
*Legges andre CSS-issues her eller på eget issue så vi kan lukke de etterhvert?*

Left padding i kollapsbare felter i geo.twig.html må fikses. Røff fiks på plass, men ingen løsning enda.
Knappe-design bør oppgraderes.

**Comment by mariusmandal** [comment]
Må være jumbo og ikke jumbo-mini som vi bruker
