### ISSUE TITLE
Statusside, klikkbare feilmeldinger

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#120]
Kan personer være klikkbare og lenke til redigeringssiden for personen med error?

**Comment by mariusmandal** [comment]
Fekk melding om at det mangla info om e-postadresse til kontaktperson undervegs i påmeldinga, men kom ikkje til sida med manglar når eg klikka på knappen for å gå tilbake og legge inn opplysningane

**Comment by AsgeirSH** [comment]
Opprettet branch iss120 for jobbing med denne.
