### ISSUE TITLE
Tekst: dans

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#124]
Titler bør ha annet navn enn dans

innslag, performance, tittel, koreografi, nummer

Sjekk med Rebecca E Sørum (URG Telemark)

Artistnavn / dansegruppe / _crew_ ?

**Comment by AsgeirSH** [comment]
Epost sendt.

**Comment by AsgeirSH** [comment]
Fått svar: 
Hei!
Beklager sent svar, er i London.

- Jeg vil anbefale dere å skrive koreografi, eventuelt innslag, fremfor dans: "legg til koreografi". Men på siste bilde, hvor det står Danser - bounce, kan "innslag" vurderes.

- artistnavn/dansegruppe passer bra, crew er et grep som kun omfavner et fåtall stiler.

Ellers ser det veldig fint og oversiktlig ut.

Mvh.
Rebecca Sørum
