### ISSUE TITLE
Tekst: teater

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#126]
Titler på din side må stemme med faktiske tittel-tekster

Tittel = nummer / sketsj / monolog

Tekst av: (valgfritt felt) har i dag attr required (_not a feature.._)
Tekst av = Hvem har skrevet manus?
   fjern hjelpetekst
Kutt melodi av

Kan vi sjekke dette med Lina T Fjørtoft?

**Comment by AsgeirSH** [comment]
Epost sendt

**Comment by AsgeirSH** [comment]
Reply:

Hei!

Ja, jeg kan godt se litt nærmere på dette. 

Jeg syns man skal være konsekvent på å kalle det gruppe hele veien, ikke teatergruppe som i første bolk. Når man har klikket seg inn på teater forstår man at gruppen driver med teater uten å kalle det teatergruppe. teatergruppe kan høres begrensende ut også. 
Om det står beskrivelse av gruppe, får dere nok en beskrivelse av selve gruppen eks: "Tre jenter fra Bergen på 13 år". Om det er det dere ønsker så kan tittelen være slik, men utfra hjelpeteksten dere har skrevet ser ønsket deres ut til å være å få beskrivelse av innslaget? Da må det stå: kort beskrivelse av innslaget


"Teaterstykke" høres veldig stort ut, som om det skal vare en god stund. Er det mulig å bare kalle det innslag?  En sketsj går også innenfor det føler jeg. 

Når det kommer til lengde er det mulig å opplyse makstid her? Opplever at det er her man blir usikker når det gjelder teaterinnslagene fordi de ofte må vare litt lenger enn en sang, men hvor lang tid har man til rådighet? Om det opplyses makstid vet man hva man skal holde seg innenfor.

Musikk blir gjerne brukt, men om det ikke er viktig å ha opplysninger om det i forhold til eventuelle rettigheter på den, så kan nok det feltet fjernes ja. Da burde det nevnes i eksempelteksten til hva teknikker må vite, at denne må få info om eventuell musikk skal spilles av. 

Dere sa at hjelpeteksten forsvinner, gjelder det alt, eller bare et sted? Om den ikke skal bort alle steder har jeg noen meninger om den også :)

Lina
