### ISSUE TITLE
Spesialtegn

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#133]
Test nordiske + ' i absolutt alle felt!

**Comment by AsgeirSH** [comment]
Funker i beskrivelse, sjanger. Sjekker hvorfor artistnavn failer.

**Comment by AsgeirSH** [comment]
La til utf8_encode i InnslagService. Nå failer innslag_navn ellers. -.-

**Comment by AsgeirSH** [comment]
Spesialtegn og apostrof:
- UKMID - Din Side - Alt funker nå per neste Asgeir-commit.
- oversikt - alt funker og takler æøå '.
- personer - alt funker og takler æøå '. Ikke testet mobilnr-inputen.
- tekniske behov - alt funker og takler æøå '.
- Titler
  - Musikk - alt funker og takler æøå '.
  -

**Comment by mariusmandal** [comment]
### Din side
- [ ] SPECIAL navn
- [ ] VALID navn
- [ ] SPECIAL beskrivelse
- [ ] VALID beskrivelse
- [ ] SPECIAL sjanger
- [ ] VALID sjanger
### Tekniske behov
- [ ] TYPE tekst
- [ ] TYPE tekst
### Personer
- [ ] SPECIAL fornavn
- [ ] VALID fornavn
- [ ] SPECIAL etternavn
- [ ] VALID etternavn
- [ ] SPECIAL mobil
- [ ] VALID mobil
- [ ] SPECIAL e-post
- [ ] VALID e-post
- [ ] SPECIAL rolle
- [ ] VALID rolle
### Musikk
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] VALID varighet
- [ ] VALID har tekst / instrumental
- [ ] VALID selvlaget
- [ ] SPECIAL tekst av
- [ ] VALID tekst av
- [ ] SPECIAL melodi av
- [ ] VALID melodi av
### Teater
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] VALID varighet
- [ ] VALID selvlaget
- [ ] SPECIAL tekst av
- [ ] VALID tekst av
### Dans
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] VALID varighet
- [ ] VALID selvlaget koreografi
- [ ] SPECIAL koreografi av
- [ ] VALID koreografi av
### Annet
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] VALID varighet
### Utstilling
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] SPECIAL type
- [ ] VALID type
- [ ] SPECIAL beskrivelse
- [ ] VALID beskrivelse
### Litteratur
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] SPECIAL medforfattere
- [ ] VALID medforfattere
- [ ] VALID varighet
- [ ] VALID ønsker lese opp
- [ ] VALID varighet
### Film
- [ ] SPECIAL tittel
- [ ] VALID tittel
- [ ] VALID varighet
