### ISSUE TITLE
Spesialtegn titler: utstilling

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#146]
Type feiler ved visning på din side, men fungerer i skjema

**Comment by AsgeirSH** [comment]
Funker hos meg. @mariusmandal

**Comment by mariusmandal** [comment]
Gjør det det i parentesen i den utvidede tittellista på din side?

**Comment by AsgeirSH** [comment]
Ah, tenkte Din Side = ukmid. Du mener type i tittel på oversikt.twig.html?

**Comment by AsgeirSH** [comment]
There we go. Skal se etter den der.

**Comment by mariusmandal** [comment]
My bad



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
ah, tittel.class kjører utf8_encode i _utstilling()-funksjonen... to ganger.
