### ISSUE TITLE
geoAction + whatAction: låst hvis frist er ute

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#160]
Hvis begge påmeldingsfrister er ute: stopp i geoAction
Hvis en av fristene er ute, skjul kategoriene for fristen i whatAction

**Comment by AsgeirSH** [comment]
Hvis begge er ute er vel implementert, men kategori-skjuling må fortsatt gjøres?

**Comment by mariusmandal** [comment]
closed by 864a776f07ab28862d07bd7ffc1da799d18a185b
