### ISSUE TITLE
CSS: Knappedesign

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#17]
Knapper som er basert på en <a href>-tag har håpløst design, tekst synes kun ved hover og bredde/farge etc må endres.

**Comment by AsgeirSH** [comment]
Delvis fikset, css finnes i DeltaBundle\Resources\public\less\delta.css. Hover må vurderes, ellers relativt greit nå.

**Comment by mariusmandal** [comment]
@AsgeirSH Vises dette ok på mobile (milestone:beta), eller må den tweakes (milestone:alpha),

**Comment by AsgeirSH** [comment]
Mobile har ikke hover(?) så vil sette milestone:beta

**Comment by mariusmandal** [comment]
UserBundle bruker a-knapper uten styling, det funker dårlig på mobil..
