### ISSUE TITLE
Tilgang til innslag ved pamelduser == null

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#176]
Hvis pamelduser == null (ikke startet påmelding) og brukeren finner innslag (ut fra b_passord == ukmdeltaID), vil brukeren få feilmelding når innslagssiden åpnes.

**Comment by mariusmandal** [comment]
Problemet "løses" når brukeren oppretter et innslag, og får pamelduser satt. Ikke god nok løsning da :)

**Comment by AsgeirSH** [comment]
Duplicate #187 - fixed.
