### ISSUE TITLE
Navn forsvinner noen ganger fra Ninja-knappen

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#179]

**Comment by AsgeirSH** [comment]
Endre user.getFirstName() til app.user.getFirstName() og den er tilgjengelig overalt. 

Feilen lå i urlen, pga routingtypo havna nettsida utenfor brannmur (umkid vs ukmid)

**Comment by mariusmandal** [comment]
whoAction mangler ninja-navn

**Comment by AsgeirSH** [comment]
Det var apparently feil i commiten- Fiksa direkte i stad.
