### ISSUE TITLE
knappe-bredde

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#182]
btn-primary / btn-default går hele skjermbredden. Må puttes i container eller noe
- [ ] whoAction
- [ ] overviewAction

**Comment by AsgeirSH** [comment]
Har eller mangler btn-block eller er inne i /ikke inne i en .row.

Sjekk knapp for tekniske.

**Comment by AsgeirSH** [comment]
Buttons i en .col-xs-12 kan ikke være i en .row. Fixed.
