### ISSUE TITLE
toppmeny

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#189]
fjern generisk meny, og bruk ninja-menyen i stedet.
ny meny
- [ ] gå til din side
- [ ] rediger din info
- [ ] endre passord
- [ ] kontakt support
- [ ] logg ut

**Comment by AsgeirSH** [comment]
Kontakt support - Trenger du hjelp?

Egen side:
De fleste spørsmål er det lokalkontakten som har svaret på, men trenger du teknisk hjelp eller har andre spørsmål kan du kontakte support på support@ukm.no - tlf: XXXX.
