### ISSUE TITLE
"Meld Av"-knapp også for innslag som er så vidt påbegynt

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#210]
Fikk support-epost med spørsmål om folk som har trykket Ny Påmelding for å lese mer om kategoriene. Mulighet for å melde av innslag som så vidt er påbegynt?

**Comment by mariusmandal** [comment]
Det er mulig på alle innslag fra deltaker-siden? (Med unntak av jobbe på UKM da, hvor det ikke er implementert..)



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox
