### ISSUE TITLE
Github-pull-skript må validere databaseskjema

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#216]
Cleare cache også?

**Comment by AsgeirSH** [comment]
RFC @mariusmandal :
Github-pull.sh-skriptet ser etter et deploy-skript med standard-navn som kan legges til i et repo.

Hvis "deploy.sh" / "deploy.php" (elns) finnes i topp-nivået etter en github-pull, kjør skriptet. Send logg til support@ukm.no med standard emne og default informasjon:
"Oppgradering til hashcode@repo - suksess" / "Oppgradering til hashcode@repo - mislykket"

**Comment by mariusmandal** [comment]
Oppdatering av delta skjer kun on-demand nå, og vi har gått bort fra autodeploy. Dette for å unngå utilsiktede feil, og sikre at vi holder et ekstra øye med delta etter endringer
