### ISSUE TITLE
Logg inn til wordpress fra delta

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#234]
Brukere som er innlogget i delta, og som har en bruker i wordpress bør få muligheten til å logge inn direkte fra Delta. 

Denne løser selve innloggingen på wordpress-siden:
https://iandunn.name/2013/12/28/programmatically-sign-on-a-wordpress-user/

Det må opprettes en tabell `delta_wp_user` i SS3-databasen med koblingen `Delta UID` - `WP UID`, som benyttes til koblingen mellom Delta og Wordpress.

Vi må vel ha en tabell `delta_wp_login_token` i SS3-databasen.
Her må det insertes en rad fra Delta, før vi sender brukeren videre til autologin-scriptet, sånn at vi vet at brukeren faktisk skal logges inn. Dette må være en engangstoken med timestamp (1 min?).
(husk å lagre sql-spørringer i https://github.com/UKMNorge/UKMapi/tree/master/_DB-migration)

I delta ser jeg for meg følgende brukerflyt:
- bruker logger inn og kommer til "din side"
- bruker trykker på knappen "logg inn i arrangørsystemet"
  - bruker sendes da til `delta.ukm.no/ukmid/`
  - token insertes i `delta_wp_login_token`
  - brukeren redirectes til `ukm.no/deltalogin/` e.l. (dette kan også være en lang url hvis det er teknisk enklere) med query params: `uid`, `tokenid`
  - token slettes (hvis funnet)
  - innlogget bruker sendes til `ukm.no/wp-admin/user/`
  - feilet innlogging dør pent
 
Ettersom en delta-bruker kan delta på flere arrangement, må UKMNorge/UKMusers#10 implementere en "aktiver"-funksjon, som legger til brukeren til sin egen WP-blogg.

**Comment by mariusmandal** [comment]
Burde vi kreve IS_FULLY_AUTH, eller hva den heter, før vi lar de logge inn til arrangørsystemet? For øyeblikket lever vel sessions så kort at det ikke er poeng @AsgeirSH ?

**Comment by AsgeirSH** [comment]
Vi har utvidet sessions-levetid ifbm skjema for videresending, ref 91d4bbd. Men IS_AUTHENTICATED_REMEMBERED er vel OK nok likevel? @mariusmandal

**Comment by mariusmandal** [comment]
Ja, det er absolutt innafor @AsgeirSH :)

**Comment by mariusmandal** [comment]
Høyst relevant info @AsgeirSH https://github.com/UKMNorge/UKMapi/commit/98ac87d120ae00eafe385effae8497c4a202eb8b

**Comment by AsgeirSH** [comment]
Note to self: Fix denne også (`Excpetion`): https://github.com/UKMNorge/UKMapi/commit/98ac87d120ae00eafe385effae8497c4a202eb8b#diff-43401d61894a8c1b4dc0d9c081fd428bR151

**Comment by AsgeirSH** [comment]
Much progress:
https://github.com/UKMNorge/UKMdelta/commit/9b2c81619d1f79bbed866cc8d6b6a38d0d4d0af6
https://github.com/UKMNorge/UKMusers/tree/feature/deltainnlogging
https://github.com/UKMNorge/UKMapi/tree/feature/deltainnlogging
https://github.com/UKMNorge/UKMresponsive/tree/feature/deltainnlogging

**Comment by AsgeirSH** [comment]
Mangler å gå til User-side ved fullført innlogging, noe logging og noe feilmeldinger. Feilmelding i Delta ved feil før redirect er OK, feil i WP etter redirect gir ingen feilmelding enda - kun redirect tilbake til Delta.

**Comment by AsgeirSH** [comment]
Delta-delen av denne er ferdig. Har lagt issuet nederst - lukker ikke før merge OK (inkl. andre repo).
