### ISSUE TITLE
Vis fylkenes arrangementer med påmelding

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#235]

**Comment by mariusmandal** [comment]
Relatert #246 og UKMNorge/UKMresponsive#119
Når fylkesarrangementer har påmelding, må lenken til påmelding vises, og delta må kunne ta i mot direkte-påmelding

**Comment by mariusmandal** [comment]
Må også være mulig å velge åpen påmelding i https://github.com/UKMNorge/UKMnettverket

**Comment by AsgeirSH** [comment]
Assigner meg selv for Delta-delen. Ser om vi rekker det ila dagen @mariusmandal

**Comment by AsgeirSH** [comment]
13 steder bruker `innslag->getKommune()` og må feilhåndtere den.

**Comment by AsgeirSH** [comment]
Hvis vi implementerer dette som tenkt kan vi ikke lenger bruke getInnslag()->getAll() i Twig uten try/catch. Mer tenking må til, utsetter denne.

**Comment by mariusmandal** [comment]
@AsgeirSH kan du skrive inn en oppdatering på hva som finnes av branches / kode, og hvor denne feilet?

**Comment by AsgeirSH** [comment]
UKMapI: https://github.com/UKMNorge/UKMapi/tree/feature/fylkespamelding
UKMdelta: https://github.com/UKMNorge/UKMdelta/tree/feature/fylkespamelding

Slik APIet er endret, vil vi ikke feile stille på `xx->getInnslag()->getAll()`, men kaster Exception på Load av Innslag-objekt. Det gjør vi mange steder i Twig, som vil si at vi ikke kan bruke try/catch for å håndtere problemene som tenkt. 

Det burde i stedet være en måte å finne ut om innslaget er en vanlig påmelding som skal ha kommune-verdi, eller om det er en "løsrevet" påmelding på noe annet.

**Comment by mariusmandal** [comment]
Fixed
