### ISSUE TITLE
Re-implementer facebook login

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#238]

**Comment by AsgeirSH** [comment]
Seems to work fine, testa i .dev. Skal teste i prod før jeg lukker, men funker fint både med og uten eksisterende bruker så langt.

**Comment by mariusmandal** [comment]
Vi har denne på test-lista @AsgeirSH så for min egen oversikt lukker jeg issuet ettersom vi antar det er ok, og den vil bli testet før launch :)
Får vi heller re-åpne om det viser seg at vi har en bug.
