### ISSUE TITLE
I dev opprettes bruker og får opprette innslag med sms_validated:0 i databasen

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#242]

**Comment by AsgeirSH** [comment]
Ser kun èn bruker i databasen som har sms_validated = 1 (heller ikke i Alpha er denne satt noe sted), og koden bruker ikke setSmsValidated()-funksjonen noe sted som jeg finner med søking. Tror vi kan lukke denne, med mindre vi ønsker å bruke den til noe.
