### ISSUE TITLE
Koble eksisterende bruker til facebook funker ikke

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#256]
https://delta.ukm.no/ukmid/fbconnect/ sier `TODO: Funksjonen er ikke implementert
i fil /home/ukmdelta/public_html/src/UKMNorge/DeltaBundle/Controller/UKMIDController.php på linje 296` og trenger litt kjærleik

**Comment by AsgeirSH** [comment]
Hvordan fremprovoserer du denne @mariusmandal ? Funker helt fint for meg å logge inn med facebook - er det hvis det mangler fb-id i databasen eller noe?

**Comment by AsgeirSH** [comment]
Ok, fant den etter litt mer leting 😄 Hvis du trykker "Koble til Facebook" i menyen bruker vi det menyvalget. Oppretting av bruker via facebook ellers oppfører seg fint.
