### ISSUE TITLE
Delta viser påmeldingsfrist som start-dato

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#260]
Etter påmelding OK. Eksempel Bergen.

**Comment by mariusmandal** [comment]
eh, hvor skjer dette @AsgeirSH? :)

**Comment by AsgeirSH** [comment]
![PetterPameldt](https://user-images.githubusercontent.com/1831028/68215087-f0d7ae00-ffde-11e9-9d3c-300698264616.jpg)
Du er påmeldt-siden.
