### ISSUE TITLE
E-post blir ikke sendt inn fra Delta til participant-tabell

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#263]
Som vil si at vi varsler om at kontaktperson mangler kontaktinfo etc når de egentlig har oppgitt dette.

Ikke sjekka i prod, men skjer lokalt hos meg.

**Comment by AsgeirSH** [comment]
Og man får opp "OBS: Du er ikke påmeldt enda". Greit å sjekke om mange dukker opp med status under 8?

**Comment by AsgeirSH** [comment]
Var en følgefeil av at bruker i _participant ikke hadde e-post. Ble funnet igjen med fornavn, etternavn og mobil.

**Comment by mariusmandal** [comment]
🥳🥳
