### ISSUE TITLE
Exception-handler må varsle support når det er ukjente exceptions

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#265]
De vi kjenner til, og lar brukeren håndtere selv kan passere i stillhet, men hvis det er en ukjent feil, er det supert om support kan starte feilsøkingen. I tillegg vil dette gi oss oversikt over hvor mange feil som oppstår.
Nyttig debug-data som bør være med i e-posten:
- [ ] route / url
- [ ] user-object
- [ ] debug_backtrace

**Comment by mariusmandal** [comment]
Relatert #258 ?

**Comment by AsgeirSH** [comment]
Unødvendig å sende med hele brukerobjektet - da eksponerer vi mye ekstra data og øker støynivået. Sender med navn og ID, så man kan uansett finne det for å se på det.
