### ISSUE TITLE
"Innslaget er påmeldt OK"-sjekken må sjekke om typen faktisk skal ha tekniske behov

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#266]
Statussiden forteller at jeg mangler både tekniske behov og beskrivelse på et dataspillgruppe-innslag.

**Comment by mariusmandal** [comment]
Og jeg som trodde jeg hadde fiksa denne 🤭

**Comment by AsgeirSH** [comment]
Du hadde fiksa denne @mariusmandal - var nok følgefeil av at innslaget ikke var relatert til mønstringen rett, ettersom jeg ikke fikk feilmeldinga nå :)

Closing.
