### ISSUE TITLE
Laste opp playbackfiler

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#28]
Bør være mulig :)

**Comment by mariusmandal** [comment]
3. Det trengs en mulighet til å laste opp singback/backingtrack/beat/film og en beskrivelse av hva slags filer vi trenger og at det er deres ansvar å gi oss riktig fil i god tid før mønstringen
4. Det trengs en mulighet til å laste opp digitale foto for de som melder seg på med foto

**Comment by AsgeirSH** [comment]
Lukkes da vi nå tar ut felt deltakerne må fylle ut - ingen grunn til å legge til enda et steg i prosessen.

Problematisk ettersom vi ikke vet hvem som har bruk for feltet og ikke, pluss at det er lenge fra påmelding til arrangement, kanskje ikke alt er på plass for deltakeren enda heller.
