### ISSUE TITLE
statusAction: bedre vei tilbake for å fikse feil

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#283]
Hvis det mangler flere ting, er det ikke en fornuftig arbeidsflyt å trykke på den enkelte feilen, da man likevel kommer tilbake til innslagssiden, og sikkert har glemt hva som mangler. Feilene må altså vises på selve siden også, og kanskje kan man ha en "gå tilbake for å fullføre"-knapp/lenke før vi lister ut hva som er feil?

**Comment by AsgeirSH** [comment]
Det er allerede en "Gå tilbake for å fylle ut det siste"-knapp - og hvis du trykker på f.eks rolle-feil nå blir du sendt til den personen det gjelder, mens beskrivelse og sjanger er de eneste som sender deg til oversikten.

**Comment by mariusmandal** [comment]
Denne har hatt flere revisjoner, og jeg tror også det er ivaretatt mer enn godt nok i ny UX-gjennomgang, som gjør at innslag-siden er enklere å navigere
