### ISSUE TITLE
Brukeren mister session / brukerobjekt ved Exception

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#293]
Av en eller annen grunn mister vi brukerobjektet dersom brukeren opplever en Exception. Men Symfony prøver likevel å åpne alle sider med "anon" uten av brannmuren slår til, som fører til flere feil der vi prøver å gjøre ting med en streng når vi forventer brukerobjekt...

cc @mariusmandal

**Comment by mariusmandal** [comment]
Jeg tror dette er i dev, pga profiler'n @AsgeirSH . Kan det stemme, tror du? Jeg tror det kallet startes, genererer ny session_id, men av en eller annen grunn mister vi noe på veien (litt som om du refresher sida før profiler'n dukker opp).
Har du sett det i prod, eller kun i dev?

**Comment by AsgeirSH** [comment]
Kun sett i dev, men det som er rart med det er at vi ikke blir redirecta til innlogging av brannmuren slik vi skal.

**Comment by mariusmandal** [comment]
Har du mulighet til å teste det i prod på noe vis, tror du @AsgeirSH ?

**Comment by AsgeirSH** [comment]
Ja, det kan jeg :)

**Comment by AsgeirSH** [comment]
Ser ikke ut til å skje i prod - lukker.

**Comment by AsgeirSH** [comment]
Har nå funnet ut mer om dette - det er vi som bevisst logger ut enkelte som får noen feil, se https://github.com/UKMNorge/UKMdelta/blob/master/src/AppBundle/EventListener/ExceptionListener.php#L93

Enten så logger vi ut personen direkte, eller så genererer vi en anon-bruker som gjør det for dem. Usikker på hvorfor vi la inn dette. Det skjer ikke for deltaExceptions som påmeldingsfrist ute, heldigvis. Men systemfeil vil fortsatt logge ut brukere.

**Comment by mariusmandal** [comment]
Hehe, spennende feature dette. Jeg prøver å tenke på hvorfor vi kan ha gjort det sånn.
Top of my head: Kan det ha med facebook-innlogging å gjøre? Hvis brukeren er i prosess med å logge inn med facebook e.l. at vi har behov for å logge vedkommende ut hvis en feil oppstår i prosessen?

**Comment by AsgeirSH** [comment]
Etter litt research: Grunnen til at vi gjorde dette var at templatene i DeltaDesignBundle / DesignBundle prøvde å bruke user-objektet uten å sjekke på riktig vis om den fantes, ref: https://github.com/UKMNorge/UKMdelta/commit/a56066139a0c19e1211ec998b4463a970993fbc6

Nå fungerer tydeligvis ikke dette helt godt nok heller, men velger å tro at vi med 0d320a79 klarer å skape en greiere brukeropplevelse.

Du får også timestamp i nye e-poster med denne commiten @mariusmandal .
