### ISSUE TITLE
Pull og test

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#299]
- [x] statusAction (test et innslag med mange mangler. Så lenge det ikke kræsjer siden: pass)
- [x] listen med innslag viser både innslag som er og ikke er fullstendig påmeldt

Endret kode:
fa5e2b3a0c507c9f719e295207e8a109e4f3af1d

**Comment by AsgeirSH** [comment]
Testet ok i 70c9988
