### ISSUE TITLE
Sjekk at mangler funker som den skal

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#300]
Filter var feil implementert tidligere, men kan ha slått til riktig likevel
2e0d5bd31d9ab35a2f1e67334a72852c37ed730f

**Comment by AsgeirSH** [comment]
Related #302

**Comment by AsgeirSH** [comment]
Arrangør/Nettred uten noen rolle krasjer. Fixed 👍 Linken sender oss til rediger person, i stedet for rediger innslag. Fixed 👍 
Alle mangler for Annet funker OK.
Alle manger for Musikk/Dans funker OK.
Alle mangler for Utstilling funker OK - men navnet for rolle er kanskje litt for uheldig i det tilfellet her: `1. Funksjon/rolle/instrument mangler` ?

For en dataspill (gruppe)-påmelding (altså dynamisk kategori) får jeg ikke opp mangel på manglende rolle. Usikker på hvor dette defineres @mariusmandal ? Mulig det er fordi den ikke er definert til å ha funksjoner?
