### ISSUE TITLE
Delta kan ikke vise skjulte arrangementer!

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#305]
not arrangement->erSynlig() == continue

**Comment by AsgeirSH** [comment]
Fixed in aa48f1c.

**Comment by AsgeirSH** [comment]
Reopen - feil issue-tag i commit.

**Comment by mariusmandal** [comment]
menmen, hæ? Var ikke denne riktig lukka @AsgeirSH ? 😄

aa48f1cee3a1da30cea4d4dd1d3ca2a943e81322 bytter ut `getAll()` med `getAllSynlige()`

**Comment by mariusmandal** [comment]
og er da #304 rioktig lukka?

**Comment by AsgeirSH** [comment]
Øøh, her har det skjedd noe krøll. Lukka #304 med feil tag, skulle gjenåpne det, men har tydeligvis gjenåpna denne på et vis 😓

Faktisk status: Denne er fiksa nå, mens #304 venter på merge av PR #306

**Comment by mariusmandal** [comment]
👍🏼 merger morgen @AsgeirSH
