### ISSUE TITLE
Ny-kobling av bruker og deltaker må oppdatere delta_wp_user

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#307]
Fordi noen wordpress-brukere kan opprettes for en deltaker uten delta-bruker, er det viktig at relasjonstabellen `delta_wp_user` oppdateres med `deltaId` hvor `pId` == ny `pameld_user` i de tilfeller vi slår sammen brukere.

---
Fordi noen innslag kan være påmeldt av admin (og dermed ha en rad i `ss3DB.smartukm_participant`, men ikke i `deltaDB.ukm_user`), må `delta_wp_user` også ha feltet `PID`

_Originally posted by @mariusmandal in https://github.com/UKMNorge/UKMusers/issues/10#issuecomment-569655438_

**Comment by mariusmandal** [comment]
Skjer her:
https://github.com/UKMNorge/UKMdelta/blob/master/src/UKMNorge/APIBundle/Services/PersonService.php#L83

Som brukes av disse to:
https://github.com/UKMNorge/UKMdelta/blob/a2a7d3abc81914b326ea21f99ed586c5cc34dbbd/src/UKMNorge/DeltaBundle/Controller/InnslagController.php#L168
og 
https://github.com/UKMNorge/UKMdelta/blob/88c0f8099e9ba50a9340183f7eae3348720e42aa/src/UKMNorge/DeltaBundle/Controller/NominasjonController.php#L294

**Comment by AsgeirSH** [comment]
Fixed by #234 when merged. Closing.
