### ISSUE TITLE
Delta feiler på å lagre person i innslaget

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#316]
```
En ukjent feil har oppstått i Delta! 
Debug-informasjon: 
Exception: PERSONER: Kunne ikke finne person 123441 i innslag 174164 
Route: /ukmid/pamelding/1122-5721/film/174164/p123441/lagre/ 
User: [***], 
ID: 1794
```

Logger vi mer her nå @AsgeirSH, slik at vi har mer tilgjengelig informasjon å lete i?
Kan problemet være at vi prøver å opprette innslag uten at `andre-param==true`, og at den dermed ikke finner det? (tror egentlig ikke det, men)

**Comment by mariusmandal** [comment]
Enda en case:
```
Debug-informasjon: 
Exception: PERSONER: Kunne ikke finne person 98084843 i innslag 174491 
Route: /ukmid/pamelding/4601-5683/musikk/174491/p98084843/lagre/ 
User: [***], 
ID: 25491
```

**Comment by mariusmandal** [comment]
Og
```
Debug-informasjon: 
Exception: PERSONER: Kunne ikke finne person 98083465 i innslag 170909
Route: /ukmid/pamelding/4203-5616/musikk/170909/p98083465/lagre/ 
User: [***],
ID: 24669
```

**Comment by AsgeirSH** [comment]
Ingenting i loggen på noen av disse som gir mer info. Vi burde ha flere log->info() i den vanlige flyten, så ville de blitt lagret dersom feil oppsto.

Finner ingen link mellom innslag 170909 og _noen_ personer. Mulig brukeren har slettet eneste person ved et feiltrykk, så avbrutt / gått tilbake en side og trykt lagre? Det er det nærmeste jeg kommer et sannsynlig scenarie. Vi kunne eksperimentert med å fjerne Meld Av-knappen (kun hatt den på Din Side) og sett om frekvensen av denne feilen gikk ned. Legger uansett inn NOTICE-log på enhver åpning av /slett/-URL. Tror kanskje ikke Confirm-funksjonalitet funker på mobil.

**Comment by AsgeirSH** [comment]
Fant 174491 i access-loggen. Der har brukeren først vært inne på `p98084843/fjern` - og litt senere åpnet `p98084843` _igjen_. Kan type på at man blar seg fram og tilbake, kanskje?

**Comment by AsgeirSH** [comment]
Fixed by be546ea479 og f107ea67d258.

Reopen om du får flere av disse nå @mariusmandal.
