### ISSUE TITLE
Det er mulig å submitte person-skjema med tomt fornavn

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#317]
Og det burde det ikke være..
Kan det være at required ikke er god nok sikring?

**Comment by AsgeirSH** [comment]
Kommer av at requesten er en GET - finner lite i POST-felt da.

Submits med GET kan være brukere som har fått en feil, blitt logget ut, og blitt redirectet tilbake etter innlogging. Vi prøver å legge til POST-krav i symfony-routing, og ser om det er godt nok. Evnt må vi håndtere å sende brukeren tilbake til skjemaet om det ikke gir en bra nok brukeropplevelse med symfony-routing.
