### ISSUE TITLE
Påmelding må håndtere ikke-eksisterende kommuner

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#329]
Kommune-objektet kan finne ut hvem som har overtatt for seg selv, og en videresending bør derfor skje.

Problemet oppstår i route `ukm_delta_ukmid_pamelding_v2_opprett` når oppgitt kommune-id er deaktivert. 
Feilmelding:
```log
En ukjent feil har oppstått i Delta 2020-03-02 21:14:12. 
Debug-informasjon: 
Exception: 0, 
MONSTRING_V2: Oppretting av objekt krever numerisk id eller databaserad 
Route: /ukmid/pamelding/1648-5003/musikk/[**obfuscated**]/ 
User: Sol[**obfuscated**]en,
ID: [**obfuscated**] 
Debug backtrace: 


#0 php-includes/UKM/Innslag/Innslag.php(126): UKMNorge\Arrangement\Arrangement->__construct(NULL) 
#1 src/UKMNorge/APIBundle/Services/InnslagService.php(145): UKMNorge\Innslag\Innslag::getById([***obfuscated***], true) 
#2 src/UKMNorge/DeltaBundle/Controller/InnslagController.php(248): UKMNorge\APIBundle\Services\InnslagService->hent([***obfuscated***]) 
#3 var/bootstrap.php.cache(3276): UKMNorge\DeltaBundle\Controller\InnslagController->overviewAction(1648, 5003, Object(UKMNorge\Innslag\Typer\Type), [***obfuscated***]) 
#4 var/bootstrap.php.cache(3235): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#5 var/bootstrap.php.cache(3389): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#6 var/bootstrap.php.cache(2594): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#7 web/app.php(27): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#8 {main}
```

Når vi treffer deaktiverte kommuner her, bør vi finne riktig id, og videresende til samme route, men med riktig kommune-ID.

Kan også gjelde flere routes, så det bør sjekkes samtidig.

**Comment by mariusmandal** [comment]
kommune har funksjonen `getOvertattAv()` som kan brukes til dette:
https://github.com/UKMNorge/UKMapi/blob/master/Geografi/Kommune.php#L328

**Comment by AsgeirSH** [comment]
Skjønner ikke hvordan brukeren kan ha kommet seg så langt som dette. Hadde h*n et innslag i en kommune som så ble slettet? I sted-velgeren velger vi jo kun blant kommuner som har mønstring. @mariusmandal

**Comment by mariusmandal** [comment]
Google is your friend, I suppose 😕 Ganske sikker på at det kommer fra gamle søkeresultater

**Comment by mariusmandal** [comment]
## Reprodusere feilen

Start påmelding til arrangement `5003` i kommune `1648`. 
https://delta.ukm.dev/app_dev.php/ukmid/pamelding/1648-5003/

Siden kommune 1648 ikke er aktiv, får vi et issue her, altså.

**Comment by mariusmandal** [comment]
## Løsningsforslag
**Tilnærming**: koding

Håndter problemet i [InnslagController::typeAction](https://github.com/UKMNorge/UKMdelta/blob/master/src/UKMNorge/DeltaBundle/Controller/InnslagController.php#L131)

1. Sjekk om kommunen er deaktivert
2. Hvis deaktivert, videresend brukeren til kommunesiden

ca 
```php
redirect( $deaktivert_kommune->getOvertattAv()->getLink() );
```
