### ISSUE TITLE
Finn en måte å gjøre feilrapportering ved Actions på.

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#34]
Eksempel deleteTitleAction;

Sletter objektet, hvordan si fra ved suksess eller failure? For øyeblikket redirect til oversikt ved suksess, til redigering ved feil.

**Comment by mariusmandal** [comment]
Set flashbag
$this->container->getFlashBag()->set('danger', 'En feil oppsto ved sletting av tittel. Forsøk igjen, og kontakt [a]support[/a] hvis problemet fortsetter');

Alle view / "mother"-view må ha en flashbag-viser:
        {% for type, messages in app.session.flashBag.all %}
            {% for message in messages %}
                <div class="{{ type }}">
                    {{ message|trans }}
                </div>
            {% endfor %}
        {% endfor %}

**Comment by AsgeirSH** [comment]
$this->addFlash('danger', 'tekst') funker.

**Comment by AsgeirSH** [comment]
FlashBag-messages er ikke stylet...?

**Comment by AsgeirSH** [comment]
Og legg inn translation. Ellers løst.
