### ISSUE TITLE
Spesialtegn i innslagsnavn

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#45]
utf8_encode mangler ett sted (kjører vi f.eks get på innslagsnavnet, eller adresseres feltet direkte?)

Apostrof i navnet forhindrer lagring (og kan gi uventede issues?)

**Comment by AsgeirSH** [comment]
SQLins-klassen setter dette rett i spørringa - uten noe validering eller fjerning av html-tegn etc. Kanskje verdt å se på?
```php
## set new values
for($i=0; $i<sizeof($this->keys); $i++) {
	$sql .= "`".$this->keys[$i]."` = '".$this->vals[$i]."', ";
}
```

**Comment by mariusmandal** [comment]
Jupp. Se construtor for SQL-klassen (heter SQL)



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox

**Comment by AsgeirSH** [comment]
Jupp som i, ja, det er her problemet ligger, ta løsningen fra SQL-klassen, eller Jupp som i jo, dette funker og er ikke det egentlige problemet?

**Comment by mariusmandal** [comment]
Problemet ligger her, cooy fra sql



Mvh,


Marius Mandal

92837360

mariusmandal@gmail.com


—Sent from Mailbox
