### ISSUE TITLE
Beskjed fra lokalkontakten

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdelta#75]
Felt på Påmeldt-siden:

"Viktig beskjed fra lokalkontakten:"
"blablabla, gå rundt svingen, husk playback, blabla".

**Comment by mariusmandal** [comment]
Husk integrering i mønstringsmodulen

**Comment by mariusmandal** [comment]
I ny påmelding går brukeren alltid via kommunesiden
