### ISSUE TITLE
Film: tittel: mangler format

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#78]
Burde format fortsatt være med?
F.eks AVI, MOV, DVD, HDV-tape, DV-tape

**Comment by mariusmandal** [comment]
Foreslår at vi dropper feltet "format", da det mest sannsynlig ikke gir noen særlig merverdi for lokalarrangører.
I V2 / V3 vil vi også ha støtte for filopplasting, noe som medfører at feltet blir overflødig.
@torsteinsiegel enig?

### Gammelt
<img width="565" alt="skjermbilde 2015-11-16 14 05 15" src="https://cloud.githubusercontent.com/assets/4747102/11182450/31693b64-8c6b-11e5-949b-f7437df7ee4b.png">
### Nytt
<img width="436" alt="skjermbilde 2015-11-16 14 07 10" src="https://cloud.githubusercontent.com/assets/4747102/11182465/57512c10-8c6b-11e5-9cf3-a8165fd51852.png">

**Comment by torsteinsiegel** [comment]
Enig
T

Fra: Marius Mandal [mailto:notifications@github.com]
Sendt: 16. november 2015 14:08
Til: UKMNorge/UKMdelta <UKMdelta@noreply.github.com>
Kopi: Torstein Siegel <torstein@ukm.no>
Emne: Re: [UKMdelta] Film: tittel: mangler format (#78)


Foreslår at vi dropper feltet "format", da det mest sannsynlig ikke gir noen særlig merverdi for lokalarrangører.
I V2 / V3 vil vi også ha støtte for filopplasting, noe som medfører at feltet blir overflødig.
@torsteinsiegel<https://github.com/torsteinsiegel> enig?

Gammelt

[skjermbilde 2015-11-16 14 05 15]<https://cloud.githubusercontent.com/assets/4747102/11182450/31693b64-8c6b-11e5-949b-f7437df7ee4b.png>

Nytt

[skjermbilde 2015-11-16 14 07 10]<https://cloud.githubusercontent.com/assets/4747102/11182465/57512c10-8c6b-11e5-9cf3-a8165fd51852.png>
