### ISSUE TITLE
Liste over innslag kan ikke wrappes i a

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdelta#87]
a-taggen bryter HTML-standard + liste-design
https://github.com/UKMNorge/UKMdelta/blob/master/src/UKMNorge/DeltaBundle/Resources/views/UKMID/index.html.twig#L25

**Comment by AsgeirSH** [comment]
Fikset med this-is-js etc ( se https://github.com/UKMNorge/UKMdelta/blob/master/src/UKMNorge/DeltaBundle/Resources/views/UKMID/innslag.html.twig#L12). 
Close
